apiVersion: apps/v1
kind: Deployment
metadata:
  name: ner-deployment
  labels:
    app: ner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ner
  template:
    metadata:
      labels:
        app: ner
    spec:
      containers:
      - name: ner
        image: gcr.io/norwegian-language-bank/ner:46494350-3686-4fa1-992e-4f810f2a05a4
        command: [ "/bin/bash" ]
        args: [ "-c", "streamlit run spacy_pos.py --server.port 8501 --server.baseUrlPath /ner --browser.gatherUsageStats=False"]
        ports:
        - containerPort: 8501
        resources:
          limits:
            cpu: 1
            ephemeral-storage: 256Mi
            memory: 6Gi
          requests:
            cpu: 1
            ephemeral-storage: 256Mi
            memory: 6Gi